version: '3'
services:
  nginx:
    build: ./client
    depends_on:
      - backend

# Extend the services from the server-compose.yml file
extends:
  file: /server/docker-compose.yml
  service: backend
