version: '3.4'

services:
  django:
    build:
      context: .
      dockerfile: ./server/Dockerfile.debug
      args:
        SUPERUSER_USERNAME: ${SUPERUSER_USERNAME}
        SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
        SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
    environment:
      - SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    ports:
      - 8000:8000
      - 5678:5678
    env_file:
      - .env
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    depends_on:
      - postgres
      - redis
    volumes:
      - static:/static
      - ${DATA_VOLUME}:/app/data

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ${DATA_VOLUME}:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    build: ./client
    ports:
      - 80:80
    volumes:
      - static:/static
    depends_on:
      - django

volumes:
  local_data:
    driver: local
  smb_data:
    driver_opts:
      type: cifs
      o: "username=${SMB_USERNAME:-},password=${SMB_PASSWORD:-}"
      device: "${SMB_ADDRESS:-}"
  static:

