version: '3'
services:
  nginx:
    build: ./nginx # Specify the path to your Nginx Dockerfile
    depends_on:
      - server

# Extend the services from the server-compose.yml file
extends:
  file: /server/docker-compose.yml
  service: server
