# Generated by Django 4.2.3 on 2023-07-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('th_sens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50)),
                ('group_description', models.CharField(max_length=200)),
                ('group_creation_date', models.DateTimeField(auto_now_add=True)),
                ('group_last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='th_groups.groupdetails')),
                ('member_id', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupLinkedSensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='th_groups.groupdetails')),
                ('sensor_id', models.ManyToManyField(related_name='group_linked_sensors', to='th_sens.sensordetails')),
            ],
        ),
        migrations.CreateModel(
            name='GroupAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins_id', models.ManyToManyField(related_name='group_admins', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='th_groups.groupdetails')),
            ],
        ),
    ]
