version: '3'

services:
  django:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - 6379:6379
