version: '3'

services:
  django:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      ${STORE_MODE:-local_data}:/app/data

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      ${STORE_MODE:-local_data}:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379

volumes:
  local_data:  # Local volume for data when SMB is not configured
  smb_data:
    driver_opts:
      type: cifs
      o: "username=${SMB_USERNAME:-},password=${SMB_PASSWORD:-}"
      device: "${SMB_ADDRESS:-}"
