# Generated by Django 4.2.3 on 2023-09-07 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('th_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='th_user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='th_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='th_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='th_user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='th_user',
            name='add_sensor_pin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='th_user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='th_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='th_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='th_user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='th_user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='th_user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
